"""Seed dataset of historical events for the timeline app.

Years use astronomical numbering: BCE years are negative (e.g. 753 BCE -> -753).
This keeps the year field numeric and sortable for plotting.

Each event has a `leads_to` line - a short bridge to what it set in motion -
so browsing chronologically reads as a narrative rather than a trivia list.
"""

# Approximate territorial extent of Roman-controlled land at milestone years,
# in square kilometers. Ancient territorial figures are inherently fuzzy and
# historians disagree on exact numbers - these are illustrative estimates
# based on commonly cited figures, not precise measurements. Extent is tracked
# for the (Western) Roman state itself and drops to 0 after its 476 CE collapse,
# even though later "Rome" events on the timeline are about its cultural legacy.
TERRITORY = [
    {"year": -753, "km2": 2, "note": "Founding: just the city itself"},
    {"year": -500, "km2": 5_000, "note": "Early Republic controls Latium"},
    {"year": -338, "km2": 10_000, "note": "Rome dominates the Latin League"},
    {"year": -264, "km2": 325_000, "note": "Rome controls the Italian peninsula"},
    {"year": -201, "km2": 800_000, "note": "Rome wins the Second Punic War"},
    {"year": -146, "km2": 1_950_000, "note": "Carthage and Corinth destroyed; Mediterranean dominance begins"},
    {"year": -44, "km2": 2_750_000, "note": "Caesar's conquests near their height"},
    {"year": 14, "km2": 4_200_000, "note": "Augustus dies, having nearly doubled the empire"},
    {"year": 117, "km2": 5_000_000, "note": "Trajan - the empire's greatest extent"},
    {"year": 200, "km2": 4_400_000, "note": "Severan era - still vast, but plateauing"},
    {"year": 284, "km2": 3_600_000, "note": "Diocletian ends the Crisis of the Third Century"},
    {"year": 395, "km2": 4_000_000, "note": "Empire splits permanently into East and West"},
    {"year": 476, "km2": 0, "note": "The Western Roman Empire collapses"},
    {"year": 1190, "km2": 0, "note": "The empire is gone - but its sayings live on"},
]

EVENTS = [
    # --- Rome ---
    {
        "title": "Founding of Rome",
        "year": -753,
        "display_date": "753 BCE",
        "category": "Rome",
        "icon": "🐺",
        "summary": "Legendary founding of the city by Romulus, who allegedly kills his twin brother Remus in a dispute over where to build.",
        "leads_to": "Centuries of expansion later, Rome's growing power draws the attention of its greatest rival: Carthage.",
    },
    {
        "title": "Hannibal Crosses the Alps",
        "year": -218,
        "display_date": "218 BCE",
        "category": "Rome",
        "icon": "🐘",
        "summary": "Carthaginian general Hannibal leads an army, including war elephants, over the Alps to invade Italy during the Second Punic War.",
        "leads_to": "Even after losing the war, Hannibal's invasion leaves Rome so shaken that one senator spends the rest of his life demanding Carthage be wiped off the map.",
    },
    {
        "title": "\"Carthago Delenda Est\"",
        "year": -146,
        "display_date": "146 BCE",
        "category": "Rome",
        "icon": "🏚️",
        "summary": "Cato the Elder ends every Senate speech with \"Carthago delenda est\" - Carthage must be destroyed. Rome finally besieges and razes the city at the end of the Third Punic War.",
        "leads_to": "With Carthage gone and the Mediterranean secured, Rome turns inward - and runs headlong into a slave revolt that nearly brings the Republic to its knees.",
    },
    {
        "title": "Spartacus's Revolt",
        "year": -73,
        "display_date": "73-71 BCE",
        "category": "Rome",
        "icon": "🔓",
        "summary": "The gladiator Spartacus leads an army of escaped slaves that defeats multiple Roman legions before being crushed - later immortalized in film and TV as a symbol of rebellion against Rome.",
        "leads_to": "The revolt is crushed, but the panic it causes among Rome's elite helps fuel the rise of ambitious generals like a young Julius Caesar.",
    },
    {
        "title": "Caesar's Conquest of Gaul",
        "year": -58,
        "display_date": "58-50 BCE",
        "category": "Rome",
        "icon": "⚔️",
        "summary": "Julius Caesar conquers Gaul over nearly a decade of campaigning, cementing his military reputation and wealth.",
        "leads_to": "That same campaign becomes the textbook case for Rome's favorite conquering trick: divide and rule.",
    },
    {
        "title": "\"Divide and Conquer\"",
        "year": -55,
        "display_date": "58-50 BCE",
        "category": "Rome",
        "icon": "🧩",
        "summary": "Caesar's Gallic Wars showcase Rome's signature strategy of exploiting rivalries among enemies to conquer them piecemeal - later distilled into the maxim \"divide et impera,\" divide and rule.",
        "leads_to": "Flush with wealth and a battle-hardened army from Gaul, Caesar is about to make a decision that breaks Rome apart.",
    },
    {
        "title": "Caesar Crosses the Rubicon",
        "year": -49,
        "display_date": "49 BCE",
        "category": "Rome",
        "icon": "🎲",
        "summary": "Caesar leads his army across the Rubicon River into Italy, an act of war against the Senate. \"Alea iacta est\" - the die is cast.",
        "leads_to": "Caesar's illegal invasion of Italy chases his rival Pompey all the way to Egypt - and into Cleopatra's court.",
    },
    {
        "title": "Caesar and Cleopatra",
        "year": -48,
        "display_date": "48 BCE",
        "category": "Rome",
        "icon": "👑",
        "summary": "Caesar arrives in Egypt pursuing his rival Pompey and becomes entangled with Cleopatra, backing her claim to the Egyptian throne.",
        "leads_to": "Caesar barely has time to settle Egypt's throne before he's off crushing another rebellion in the east.",
    },
    {
        "title": "\"Veni, Vidi, Vici\"",
        "year": -47,
        "display_date": "47 BCE",
        "category": "Rome",
        "icon": "🏆",
        "summary": "Caesar reports his lightning victory over King Pharnaces II at the Battle of Zela in three words: \"I came, I saw, I conquered.\"",
        "leads_to": "Caesar's unchecked power and endless victories are exactly what convince a group of senators he has to die.",
    },
    {
        "title": "Assassination of Julius Caesar",
        "year": -44,
        "display_date": "44 BCE",
        "category": "Rome",
        "icon": "🗡️",
        "summary": "Caesar is stabbed to death by a group of senators, including Brutus, on the Ides of March. \"Et tu, Brute?\"",
        "leads_to": "Caesar's death doesn't end the chaos - it ignites a civil war between his heir Octavian and his ally Mark Antony, who's fallen for Cleopatra.",
    },
    {
        "title": "Battle of Actium",
        "year": -31,
        "display_date": "31 BCE",
        "category": "Rome",
        "icon": "⚓",
        "summary": "Octavian's fleet crushes the combined forces of Mark Antony and Cleopatra, deciding the fate of Rome and Egypt.",
        "leads_to": "With his fleet destroyed, Antony's alliance with Cleopatra collapses along with any hope of holding Egypt.",
    },
    {
        "title": "Death of Cleopatra",
        "year": -30,
        "display_date": "30 BCE",
        "category": "Rome",
        "icon": "🐍",
        "summary": "Cleopatra VII, last pharaoh of Egypt, dies by suicide (legend says by asp bite) as Octavian's forces take Alexandria, ending Ptolemaic Egypt.",
        "leads_to": "With his last rivals gone, Octavian is the only power left standing in Rome.",
    },
    {
        "title": "Augustus and the Pax Romana",
        "year": -27,
        "display_date": "27 BCE",
        "category": "Rome",
        "icon": "🏛️",
        "summary": "Octavian is granted the title Augustus and becomes Rome's first emperor, beginning two centuries of relative peace and stability.",
        "leads_to": "The peace and prosperity of Augustus's reign gives poets like Horace room to write about something other than war.",
    },
    {
        "title": "\"Carpe Diem\" Coined",
        "year": -23,
        "display_date": "23 BCE",
        "category": "Rome",
        "icon": "⏳",
        "summary": "The poet Horace writes \"carpe diem\" - seize the day - in his Odes, coining one of the most quoted phrases in the world.",
        "leads_to": "Augustus isn't just reshaping culture - he's rebuilding the empire's infrastructure, starting with the road network radiating from Rome itself.",
    },
    {
        "title": "\"All Roads Lead to Rome\"",
        "year": -20,
        "display_date": "20 BCE",
        "category": "Rome",
        "icon": "🛣️",
        "summary": "Augustus erects the Milliarium Aureum, the Golden Milestone, in the Forum - the symbolic point from which every road in the empire was measured, and the real-world root of the proverb.",
        "leads_to": "Decades later, Augustus's stable empire gives way to a very different kind of emperor.",
    },
    {
        "title": "Caligula's Reign of Terror",
        "year": 41,
        "display_date": "37-41 CE",
        "category": "Rome",
        "icon": "🤪",
        "summary": "Emperor Caligula declares himself a living god, terrorizes the Senate, and allegedly threatens to make his horse a consul - until his own bodyguards assassinate him in 41 CE.",
        "leads_to": "Rome badly needs stability after Caligula - and finds a steadier, if reluctant, emperor in his uncle Claudius.",
    },
    {
        "title": "\"We Who Are About to Die Salute You\"",
        "year": 52,
        "display_date": "52 CE",
        "category": "Rome",
        "icon": "🤺",
        "summary": "Condemned fighters reportedly greet Emperor Claudius with \"Ave Imperator, morituri te salutant\" before a staged naval battle - a phrase now inseparable from pop culture's idea of the gladiator.",
        "leads_to": "That same appetite for spectacle turns dark under Claudius's successor, whose reign becomes a byword for tyranny.",
    },
    {
        "title": "Nero and the Great Fire of Rome",
        "year": 64,
        "display_date": "64 CE",
        "category": "Rome",
        "icon": "🔥",
        "summary": "A massive fire destroys much of Rome while Nero, according to legend, fiddles as the city burns. He blames - and brutally persecutes - the city's Christians, cementing his reputation as history's archetypal tyrant.",
        "leads_to": "Rome's stability returns under the more disciplined Flavian emperors - just in time for disaster to strike a city south of Rome.",
    },
    {
        "title": "Vesuvius Erupts, Pompeii Buried",
        "year": 79,
        "display_date": "79 CE",
        "category": "Rome",
        "icon": "🌋",
        "summary": "Mount Vesuvius erupts and buries Pompeii and Herculaneum in ash, preserving them - and their residents - almost perfectly for archaeologists.",
        "leads_to": "The year after Pompeii is buried, Rome opens its most famous arena for entertainment: the Colosseum.",
    },
    {
        "title": "The Colosseum Opens",
        "year": 80,
        "display_date": "80 CE",
        "category": "Rome",
        "icon": "🏟️",
        "summary": "The Flavian Amphitheatre opens with 100 days of games, hosting gladiatorial combat for the next several centuries.",
        "leads_to": "Free games at the Colosseum become exhibit A for a satirist's complaint about how Rome keeps its public pacified.",
    },
    {
        "title": "\"Bread and Circuses\"",
        "year": 100,
        "display_date": "c. 100 CE",
        "category": "Rome",
        "icon": "🎪",
        "summary": "Satirist Juvenal coins \"panem et circenses\" - bread and circuses - describing how free food and games kept the Roman public docile.",
        "leads_to": "Decades later, Rome briefly finds its most philosophical ruler yet.",
    },
    {
        "title": "Marcus Aurelius Writes His Meditations",
        "year": 170,
        "display_date": "c. 170 CE",
        "category": "Rome",
        "icon": "🧘",
        "summary": "While commanding troops on the frontier, Emperor Marcus Aurelius privately writes Meditations - Stoic reflections that make him history's model of the philosopher-king.",
        "leads_to": "The stability of Aurelius's rule doesn't last - within decades Rome slides into a century of crisis, until an emperor claims a battlefield vision that changes everything.",
    },
    {
        "title": "Constantine's Vision at the Milvian Bridge",
        "year": 312,
        "display_date": "312 CE",
        "category": "Rome",
        "icon": "✨",
        "summary": "Before a decisive battle, Constantine reportedly sees a cross of light in the sky with the words \"in this sign, conquer.\" He wins, and credits the Christian God.",
        "leads_to": "Convinced Christianity's God won him the battle, Constantine legalizes the religion the following year.",
    },
    {
        "title": "Edict of Milan",
        "year": 313,
        "display_date": "313 CE",
        "category": "Rome",
        "icon": "✝️",
        "summary": "Emperor Constantine legalizes Christianity throughout the Roman Empire, ending centuries of persecution.",
        "leads_to": "Christianity's new legitimacy sets off centuries of debate over how the faith should actually be practiced - starting with something as small as which day to fast.",
    },
    {
        "title": "\"When in Rome...\"",
        "year": 390,
        "display_date": "c. 390 CE",
        "category": "Rome",
        "icon": "🤷",
        "summary": "Augustine asks Bishop Ambrose of Milan why Rome fasts on Saturdays but Milan doesn't. Ambrose's reply is later paraphrased into \"when in Rome, do as the Romans do.\"",
        "leads_to": "Long after the empire falls, medieval Europe is still coining proverbs about the city that once ruled it all.",
    },
    {
        "title": "\"Rome Wasn't Built in a Day\"",
        "year": 1190,
        "display_date": "c. 1190 CE",
        "category": "Rome",
        "icon": "🧱",
        "summary": "The proverb first appears in a medieval French collection - \"Rome ne fu pas faite toute en un jour\" - capturing how the city, and the empire, actually grew gradually over centuries.",
        "leads_to": "Centuries after it fell, the empire's rise and fall is still the reference point the world reaches for when talking about power, decline, and everything in between.",
    },

]
