"""Seed dataset of historical events for the timeline app.

Years use astronomical numbering: BCE years are negative (e.g. 753 BCE -> -753).
This keeps the year field numeric and sortable for plotting.

Each event has a `leads_to` line - a short bridge to what it set in motion -
so browsing chronologically reads as a narrative rather than a trivia list.
"""

# Approximate territorial extent of Roman-controlled land at milestone years,
# in square kilometers. Ancient territorial figures are inherently fuzzy and
# historians disagree on exact numbers - these are illustrative estimates
# based on commonly cited figures, not precise measurements. Extent is tracked
# for the (Western) Roman state itself and drops to 0 after its 476 CE collapse.
TERRITORY = [
    {"year": -753, "km2": 2, "note": "Founding: just the city itself"},
    {"year": -500, "km2": 5_000, "note": "Early Republic controls Latium"},
    {"year": -338, "km2": 10_000, "note": "Rome dominates the Latin League"},
    {"year": -264, "km2": 325_000, "note": "Rome controls the Italian peninsula"},
    {"year": -201, "km2": 800_000, "note": "Rome wins the Second Punic War"},
    {"year": -146, "km2": 1_950_000, "note": "Carthage and Corinth destroyed; Mediterranean dominance begins"},
    {"year": -44, "km2": 2_750_000, "note": "Caesar's conquests near their height"},
    {"year": 14, "km2": 4_200_000, "note": "Augustus dies, having nearly doubled the empire"},
    {"year": 117, "km2": 5_000_000, "note": "Trajan - the empire's greatest extent"},
    {"year": 200, "km2": 4_400_000, "note": "Severan era - still vast, but plateauing"},
    {"year": 284, "km2": 3_600_000, "note": "Diocletian ends the Crisis of the Third Century"},
    {"year": 378, "km2": 3_000_000, "note": "Rome's legions are shattered at Adrianople"},
    {"year": 395, "km2": 2_700_000, "note": "Empire splits permanently into East and West"},
    {"year": 410, "km2": 2_000_000, "note": "Alaric sacks Rome; Britain is abandoned"},
    {"year": 452, "km2": 900_000, "note": "Vandals and Visigoths hold North Africa, Spain, and Gaul"},
    {"year": 476, "km2": 0, "note": "The Western Roman Empire collapses"},
]

# Color per dynasty/era, used by the vertical "Leaders Over Time" chart.
DYNASTY_COLORS = {
    "Roman Kingdom": "#9a9a9a",
    "Roman Republic": "#b7b0a3",
    "Late Republic": "#8c8c8c",
    "Julio-Claudian": "#c17b7b",
    "Flavian": "#5c7f97",
    "Nerva-Antonine": "#d99a3f",
    "Severan": "#9d94c4",
    "Crisis Emperors": "#a63d3d",
    "Tetrarchy": "#1f5c5c",
    "Constantinian": "#2e8b8b",
    "Valentinian": "#7fbfbf",
    "Theodosian": "#c2a05a",
}

# Individual rulers of Rome, kings through the last Western emperor. Reign
# years are simplified for readability - some co-rulers are merged into a
# single entry, and short transitional years are rounded to keep the
# sequence gapless outside of the chaotic multi-claimant CHAOS_PERIODS.
LEADERS = [
    {"name": "The Seven Kings", "start_year": -753, "end_year": -509, "dynasty": "Roman Kingdom", "five_good_emperors": False},
    {"name": "The Republic (Consuls)", "start_year": -509, "end_year": -49, "dynasty": "Roman Republic", "five_good_emperors": False},
    {"name": "Julius Caesar", "start_year": -49, "end_year": -44, "dynasty": "Late Republic", "five_good_emperors": False},
    {"name": "Augustus", "start_year": -27, "end_year": 14, "dynasty": "Julio-Claudian", "five_good_emperors": False},
    {"name": "Tiberius", "start_year": 14, "end_year": 37, "dynasty": "Julio-Claudian", "five_good_emperors": False},
    {"name": "Caligula", "start_year": 37, "end_year": 41, "dynasty": "Julio-Claudian", "five_good_emperors": False},
    {"name": "Claudius", "start_year": 41, "end_year": 54, "dynasty": "Julio-Claudian", "five_good_emperors": False},
    {"name": "Nero", "start_year": 54, "end_year": 68, "dynasty": "Julio-Claudian", "five_good_emperors": False},
    {"name": "Vespasian", "start_year": 69, "end_year": 79, "dynasty": "Flavian", "five_good_emperors": False},
    {"name": "Titus", "start_year": 79, "end_year": 81, "dynasty": "Flavian", "five_good_emperors": False},
    {"name": "Domitian", "start_year": 81, "end_year": 96, "dynasty": "Flavian", "five_good_emperors": False},
    {"name": "Nerva", "start_year": 96, "end_year": 98, "dynasty": "Nerva-Antonine", "five_good_emperors": True},
    {"name": "Trajan", "start_year": 98, "end_year": 117, "dynasty": "Nerva-Antonine", "five_good_emperors": True},
    {"name": "Hadrian", "start_year": 117, "end_year": 138, "dynasty": "Nerva-Antonine", "five_good_emperors": True},
    {"name": "Antoninus Pius", "start_year": 138, "end_year": 161, "dynasty": "Nerva-Antonine", "five_good_emperors": True},
    {"name": "Marcus Aurelius", "start_year": 161, "end_year": 180, "dynasty": "Nerva-Antonine", "five_good_emperors": True},
    {"name": "Commodus", "start_year": 180, "end_year": 192, "dynasty": "Nerva-Antonine", "five_good_emperors": False},
    {"name": "Septimius Severus", "start_year": 193, "end_year": 211, "dynasty": "Severan", "five_good_emperors": False},
    {"name": "Caracalla", "start_year": 211, "end_year": 217, "dynasty": "Severan", "five_good_emperors": False},
    {"name": "Macrinus", "start_year": 217, "end_year": 218, "dynasty": "Severan", "five_good_emperors": False},
    {"name": "Elagabalus", "start_year": 218, "end_year": 222, "dynasty": "Severan", "five_good_emperors": False},
    {"name": "Severus Alexander", "start_year": 222, "end_year": 235, "dynasty": "Severan", "five_good_emperors": False},
    {"name": "Aurelian", "start_year": 270, "end_year": 275, "dynasty": "Crisis Emperors", "five_good_emperors": False},
    {"name": "Probus", "start_year": 275, "end_year": 282, "dynasty": "Crisis Emperors", "five_good_emperors": False},
    {"name": "Carus, Carinus & Numerian", "start_year": 282, "end_year": 284, "dynasty": "Crisis Emperors", "five_good_emperors": False},
    {"name": "Diocletian & Maximian", "start_year": 284, "end_year": 305, "dynasty": "Tetrarchy", "five_good_emperors": False},
    {"name": "Constantine the Great", "start_year": 305, "end_year": 337, "dynasty": "Constantinian", "five_good_emperors": False},
    {"name": "Constantine's Sons", "start_year": 337, "end_year": 361, "dynasty": "Constantinian", "five_good_emperors": False},
    {"name": "Julian the Apostate", "start_year": 361, "end_year": 363, "dynasty": "Constantinian", "five_good_emperors": False},
    {"name": "Jovian", "start_year": 363, "end_year": 364, "dynasty": "Constantinian", "five_good_emperors": False},
    {"name": "Valentinian I", "start_year": 364, "end_year": 375, "dynasty": "Valentinian", "five_good_emperors": False},
    {"name": "Gratian & Valentinian II", "start_year": 375, "end_year": 392, "dynasty": "Valentinian", "five_good_emperors": False},
    {"name": "Theodosius the Great", "start_year": 392, "end_year": 395, "dynasty": "Theodosian", "five_good_emperors": False},
    {"name": "Honorius", "start_year": 395, "end_year": 423, "dynasty": "Theodosian", "five_good_emperors": False},
    {"name": "Valentinian III", "start_year": 423, "end_year": 455, "dynasty": "Theodosian", "five_good_emperors": False},
]

# Chaotic multi-claimant periods, shown as callout boxes listing every name
# rather than individual bar segments.
CHAOS_PERIODS = [
    {
        "start_year": -44,
        "end_year": -27,
        "label": "Civil War",
        "names": ["Mark Antony", "Lepidus", "Octavian"],
    },
    {
        "start_year": 68,
        "end_year": 69,
        "label": "Year of the Four Emperors",
        "names": ["Galba", "Otho", "Vitellius", "Vespasian"],
    },
    {
        "start_year": 192,
        "end_year": 193,
        "label": "Year of the Five Emperors",
        "names": ["Pertinax", "Didius Julianus", "Pescennius Niger", "Clodius Albinus", "Septimius Severus"],
    },
    {
        "start_year": 235,
        "end_year": 270,
        "label": "The Military Emperors",
        "names": [
            "Maximinus Thrax", "Gordian I & II", "Pupienus & Balbinus", "Gordian III",
            "Philip the Arab", "Decius", "Trebonianus Gallus", "Aemilian",
            "Valerian", "Gallienus", "Claudius Gothicus",
        ],
    },
    {
        "start_year": 455,
        "end_year": 476,
        "label": "The Final Western Emperors",
        "names": [
            "Avitus", "Majorian", "Libius Severus", "Anthemius",
            "Olybrius", "Glycerius", "Julius Nepos", "Romulus Augustulus",
        ],
    },
]

EVENTS = [
    # --- Rome ---
    {
        "title": "Founding of Rome",
        "year": -753,
        "display_date": "753 BCE",
        "category": "Rome",
        "icon": "🐺",
        "summary": "Legendary founding of the city by Romulus, who allegedly kills his twin brother Remus in a dispute over where to build.",
        "leads_to": "For over two centuries, Rome is ruled by kings - until one of them goes too far.",
    },
    {
        "title": "Founding of the Roman Republic",
        "year": -509,
        "display_date": "509 BCE",
        "category": "Rome",
        "icon": "⚖️",
        "summary": "Furious over the rape of Lucretia, Roman nobles led by Lucius Junius Brutus overthrow King Tarquin the Proud and abolish the monarchy - replacing one king with two annually elected consuls who check each other's power.",
        "leads_to": "For nearly three centuries, Rome expands under this republican system, conquering the Italian peninsula - and starts marking its funerals with a very different kind of ceremony.",
    },
    {
        "title": "First Gladiator Games",
        "year": -264,
        "display_date": "264 BCE",
        "category": "Rome",
        "icon": "🪦",
        "summary": "The first recorded gladiator games are held in Rome - funeral games for a nobleman, with just three pairs of fighters. What starts as a solemn funerary rite honoring the dead will grow over centuries into the empire's signature spectacle.",
        "leads_to": "Within a generation, Rome is locked in an all-out war with Carthage - one that very nearly ends the Republic for good.",
    },
    {
        "title": "Hannibal Crosses the Alps",
        "year": -218,
        "display_date": "218 BCE",
        "category": "Rome",
        "icon": "🐘",
        "summary": "Carthaginian general Hannibal leads an army, including war elephants, over the Alps to invade Italy during the Second Punic War.",
        "leads_to": "Even after losing the war, Hannibal's invasion leaves Rome so shaken that one senator spends the rest of his life demanding Carthage be wiped off the map.",
    },
    {
        "title": "\"Carthago Delenda Est\"",
        "year": -146,
        "display_date": "146 BCE",
        "category": "Rome",
        "icon": "🏚️",
        "summary": "Cato the Elder ends every Senate speech with \"Carthago delenda est\" - Carthage must be destroyed. Rome finally besieges and razes the city at the end of the Third Punic War.",
        "leads_to": "With Carthage gone and the Mediterranean secured, Rome turns inward - and runs headlong into a slave revolt that nearly brings the Republic to its knees.",
    },
    {
        "title": "Spartacus's Revolt",
        "year": -73,
        "display_date": "73-71 BCE",
        "category": "Rome",
        "icon": "🔓",
        "summary": "The gladiator Spartacus leads an army of escaped slaves that defeats multiple Roman legions before being crushed - later immortalized in film and TV as a symbol of rebellion against Rome.",
        "leads_to": "The revolt is crushed, but the panic it causes among Rome's elite helps fuel the rise of ambitious generals like a young Julius Caesar.",
    },
    {
        "title": "Caesar's Conquest of Gaul",
        "year": -58,
        "display_date": "58-50 BCE",
        "category": "Rome",
        "icon": "⚔️",
        "summary": "Julius Caesar conquers Gaul over nearly a decade of campaigning, cementing his military reputation and wealth.",
        "leads_to": "That same campaign becomes the textbook case for Rome's favorite conquering trick: divide and rule.",
    },
    {
        "title": "\"Divide and Conquer\"",
        "year": -55,
        "display_date": "58-50 BCE",
        "category": "Rome",
        "icon": "🧩",
        "summary": "Caesar's Gallic Wars showcase Rome's signature strategy of exploiting rivalries among enemies to conquer them piecemeal - later distilled into the maxim \"divide et impera,\" divide and rule.",
        "leads_to": "Flush with wealth and a battle-hardened army from Gaul, Caesar is about to make a decision that breaks Rome apart.",
    },
    {
        "title": "Caesar Crosses the Rubicon",
        "year": -49,
        "display_date": "49 BCE",
        "category": "Rome",
        "icon": "🎲",
        "summary": "Caesar leads his army across the Rubicon River into Italy, an act of war against the Senate. \"Alea iacta est\" - the die is cast.",
        "leads_to": "Caesar's illegal invasion of Italy chases his rival Pompey all the way to Egypt - and into Cleopatra's court.",
    },
    {
        "title": "Caesar and Cleopatra",
        "year": -48,
        "display_date": "48 BCE",
        "category": "Rome",
        "icon": "👑",
        "summary": "Caesar arrives in Egypt pursuing his rival Pompey and becomes entangled with Cleopatra, backing her claim to the Egyptian throne.",
        "leads_to": "Caesar barely has time to settle Egypt's throne before he's off crushing another rebellion in the east.",
    },
    {
        "title": "\"Veni, Vidi, Vici\"",
        "year": -47,
        "display_date": "47 BCE",
        "category": "Rome",
        "icon": "🏆",
        "summary": "Caesar reports his lightning victory over King Pharnaces II at the Battle of Zela in three words: \"I came, I saw, I conquered.\"",
        "leads_to": "Caesar's unchecked power and endless victories are exactly what convince a group of senators he has to die.",
    },
    {
        "title": "Assassination of Julius Caesar",
        "year": -44,
        "display_date": "44 BCE",
        "category": "Rome",
        "icon": "🗡️",
        "summary": "Caesar is stabbed to death by a group of senators, including Brutus, on the Ides of March. \"Et tu, Brute?\"",
        "leads_to": "Caesar's death doesn't end the chaos - it ignites a civil war between his heir Octavian and his ally Mark Antony, who's fallen for Cleopatra.",
    },
    {
        "title": "Battle of Actium",
        "year": -31,
        "display_date": "31 BCE",
        "category": "Rome",
        "icon": "⚓",
        "summary": "Octavian's fleet crushes the combined forces of Mark Antony and Cleopatra, deciding the fate of Rome and Egypt.",
        "leads_to": "With his fleet destroyed, Antony's alliance with Cleopatra collapses along with any hope of holding Egypt.",
    },
    {
        "title": "Death of Cleopatra",
        "year": -30,
        "display_date": "30 BCE",
        "category": "Rome",
        "icon": "🐍",
        "summary": "Cleopatra VII, last pharaoh of Egypt, dies by suicide (legend says by asp bite) as Octavian's forces take Alexandria, ending Ptolemaic Egypt.",
        "leads_to": "With his last rivals gone, Octavian is the only power left standing in Rome.",
    },
    {
        "title": "Augustus and the Pax Romana",
        "year": -27,
        "display_date": "27 BCE",
        "category": "Rome",
        "icon": "🏛️",
        "summary": "Octavian is granted the title Augustus and becomes Rome's first emperor, beginning two centuries of relative peace and stability.",
        "leads_to": "The peace and prosperity of Augustus's reign gives poets like Horace room to write about something other than war.",
    },
    {
        "title": "\"Carpe Diem\" Coined",
        "year": -23,
        "display_date": "23 BCE",
        "category": "Rome",
        "icon": "⏳",
        "summary": "The poet Horace writes \"carpe diem\" - seize the day - in his Odes, coining one of the most quoted phrases in the world.",
        "leads_to": "Augustus isn't just reshaping culture - he's rebuilding the empire's infrastructure, starting with the road network radiating from Rome itself.",
    },
    {
        "title": "\"All Roads Lead to Rome\"",
        "year": -20,
        "display_date": "20 BCE",
        "category": "Rome",
        "icon": "🛣️",
        "summary": "Augustus erects the Milliarium Aureum, the Golden Milestone, in the Forum - the symbolic point from which every road in the empire was measured, and the real-world root of the proverb.",
        "leads_to": "Decades later, Augustus's stable empire gives way to a very different kind of emperor.",
    },
    {
        "title": "Caligula's Reign of Terror",
        "year": 41,
        "display_date": "37-41 CE",
        "category": "Rome",
        "icon": "🤪",
        "summary": "Emperor Caligula declares himself a living god, terrorizes the Senate, and allegedly threatens to make his horse a consul - until his own bodyguards assassinate him in 41 CE.",
        "leads_to": "Rome badly needs stability after Caligula - and finds a steadier, if reluctant, emperor in his uncle Claudius.",
    },
    {
        "title": "\"We Who Are About to Die Salute You\"",
        "year": 52,
        "display_date": "52 CE",
        "category": "Rome",
        "icon": "🤺",
        "summary": "Condemned fighters reportedly greet Emperor Claudius with \"Ave Imperator, morituri te salutant\" before a staged naval battle - a phrase now inseparable from pop culture's idea of the gladiator.",
        "leads_to": "That same appetite for spectacle turns dark under Claudius's successor, whose reign becomes a byword for tyranny.",
    },
    {
        "title": "Nero and the Great Fire of Rome",
        "year": 64,
        "display_date": "64 CE",
        "category": "Rome",
        "icon": "🔥",
        "summary": "A massive fire destroys much of Rome while Nero, according to legend, fiddles as the city burns. He blames - and brutally persecutes - the city's Christians, cementing his reputation as history's archetypal tyrant.",
        "leads_to": "Nero's suicide leaves no clear heir - and Rome's leadership promptly collapses into chaos.",
    },
    {
        "title": "The Year of the Four Emperors",
        "year": 69,
        "display_date": "69 CE",
        "category": "Rome",
        "icon": "🔄",
        "summary": "Nero's death without an heir plunges Rome into chaos: four different men - Galba, Otho, Vitellius, and finally Vespasian - claim the throne within a single year, each backed by a different army.",
        "leads_to": "Vespasian's victory ends the chaos and founds a new dynasty - just in time for disaster to strike a city south of Rome.",
    },
    {
        "title": "Vesuvius Erupts, Pompeii Buried",
        "year": 79,
        "display_date": "79 CE",
        "category": "Rome",
        "icon": "🌋",
        "summary": "Mount Vesuvius erupts and buries Pompeii and Herculaneum in ash, preserving them - and their residents - almost perfectly for archaeologists.",
        "leads_to": "The year after Pompeii is buried, Rome opens its most famous arena for entertainment: the Colosseum.",
    },
    {
        "title": "The Colosseum Opens",
        "year": 80,
        "display_date": "80 CE",
        "category": "Rome",
        "icon": "🏟️",
        "summary": "The Flavian Amphitheatre opens with 100 days of games, hosting gladiatorial combat for the next several centuries.",
        "leads_to": "Within two decades, Rome stumbles onto its most stable system yet for choosing a leader: pick the best man, not just the closest relative.",
    },
    {
        "title": "Nerva Adopts Trajan",
        "year": 97,
        "display_date": "97 CE",
        "category": "Rome",
        "icon": "🤝",
        "summary": "To avoid another succession crisis, the elderly Emperor Nerva adopts a capable general, Trajan, as his heir instead of relying on bloodline. Choosing the best successor rather than the closest relative ushers in the \"Five Good Emperors,\" Rome's most stable stretch.",
        "leads_to": "That same stability gives satirists room to complain about softer problems - like how Rome keeps its public pacified with free food and games.",
    },
    {
        "title": "\"Bread and Circuses\"",
        "year": 100,
        "display_date": "c. 100 CE",
        "category": "Rome",
        "icon": "🎪",
        "summary": "Satirist Juvenal coins \"panem et circenses\" - bread and circuses - describing how free food and games kept the Roman public docile.",
        "leads_to": "Decades later, Rome briefly finds its most philosophical ruler yet.",
    },
    {
        "title": "Marcus Aurelius Writes His Meditations",
        "year": 170,
        "display_date": "c. 170 CE",
        "category": "Rome",
        "icon": "🧘",
        "summary": "While commanding troops on the frontier, Emperor Marcus Aurelius privately writes Meditations - Stoic reflections that make him history's model of the philosopher-king.",
        "leads_to": "The stability of Aurelius's rule doesn't survive his own son - who trades governing for a much stranger obsession.",
    },
    {
        "title": "Commodus Fights in the Arena",
        "year": 192,
        "display_date": "192 CE",
        "category": "Rome",
        "icon": "🦁",
        "summary": "Emperor Commodus takes to the arena himself, fighting as a gladiator and slaughtering exotic animals while billing himself as the reincarnation of Hercules - opponents are quietly handicapped to guarantee his victories. He's strangled by his own wrestling partner before the year is out.",
        "leads_to": "His death without an heir plunges Rome into fresh chaos, kicking off the very spiral of installed-and-murdered emperors his father's philosophy once held at bay.",
    },
    {
        "title": "The Year of the Six Emperors",
        "year": 238,
        "display_date": "238 CE",
        "category": "Rome",
        "icon": "💥",
        "summary": "In a single chaotic year, six different men hold or claim imperial power as the Crisis of the Third Century spirals - a preview of the fifty years of civil war, plague, and \"barracks emperors\" installed and murdered by their own troops that follow.",
        "leads_to": "The chaos finally burns itself out under an emperor willing to try something radical: splitting the job itself.",
    },
    {
        "title": "Diocletian Splits the Empire in Four",
        "year": 284,
        "display_date": "284 CE",
        "category": "Rome",
        "icon": "👥",
        "summary": "After a half-century of chaos known as the Crisis of the Third Century, Emperor Diocletian ends it by splitting imperial rule among four co-emperors - the Tetrarchy. It stabilizes Rome, but sets a precedent for permanent division.",
        "leads_to": "Diocletian's fix buys the empire another generation - and one of those four rulers is about to have a vision that changes everything.",
    },
    {
        "title": "Constantine's Vision at the Milvian Bridge",
        "year": 312,
        "display_date": "312 CE",
        "category": "Rome",
        "icon": "✨",
        "summary": "Before a decisive battle, Constantine reportedly sees a cross of light in the sky with the words \"in this sign, conquer.\" He wins, and credits the Christian God.",
        "leads_to": "Convinced Christianity's God won him the battle, Constantine legalizes the religion the following year.",
    },
    {
        "title": "Edict of Milan",
        "year": 313,
        "display_date": "313 CE",
        "category": "Rome",
        "icon": "✝️",
        "summary": "Emperor Constantine legalizes Christianity throughout the Roman Empire, ending centuries of persecution.",
        "leads_to": "But legalizing Christianity doesn't solve Rome's deeper problem: the empire's borders are buckling under pressure that's been building for a century.",
    },
    {
        "title": "Battle of Adrianople",
        "year": 378,
        "display_date": "378 CE",
        "category": "Rome",
        "icon": "🏇",
        "summary": "A Roman army is annihilated by Gothic cavalry, and Emperor Valens is killed in battle - the worst Roman defeat in centuries, and a turning point historians often mark as the beginning of the end.",
        "leads_to": "Even reeling from military disaster, the empire's religious life carries on - within a decade, a bishop in Milan is fielding much smaller questions, like when to fast.",
    },
    {
        "title": "\"When in Rome...\"",
        "year": 390,
        "display_date": "c. 390 CE",
        "category": "Rome",
        "icon": "🤷",
        "summary": "Augustine asks Bishop Ambrose of Milan why Rome fasts on Saturdays but Milan doesn't. Ambrose's reply is later paraphrased into \"when in Rome, do as the Romans do.\"",
        "leads_to": "Even as barbarian pressure mounts on every border, Rome finally turns against one of its oldest and bloodiest traditions.",
    },
    {
        "title": "The Ban on Gladiatorial Games",
        "year": 404,
        "display_date": "c. 404 CE",
        "category": "Rome",
        "icon": "🚫",
        "summary": "According to legend, a monk named Telemachus leaps into the arena to stop a gladiator fight and is killed by the crowd or the fighters. Emperor Honorius bans gladiatorial combat shortly after, ending a tradition that began 668 years earlier.",
        "leads_to": "The ban comes too late to save the city itself - six years later, the unthinkable happens.",
    },
    {
        "title": "Alaric Sacks Rome",
        "year": 410,
        "display_date": "410 CE",
        "category": "Rome",
        "icon": "🔥",
        "summary": "Visigothic king Alaric and his army sack the city of Rome itself - the first time it's fallen to a foreign enemy in almost 800 years. The shock is so profound that Augustine writes The City of God partly in response.",
        "leads_to": "Rome survives as a symbol even as the empire keeps shrinking around it - until an even more feared invader reaches the gates of Italy.",
    },
    {
        "title": "Attila the Hun Reaches Italy",
        "year": 452,
        "display_date": "452 CE",
        "category": "Rome",
        "icon": "⚡",
        "summary": "Attila the Hun, the \"Scourge of God,\" invades Italy itself. Legend holds that Pope Leo I personally meets Attila and talks him into turning back before he reaches Rome.",
        "leads_to": "Attila retreats, but the empire he spared is now a shadow of itself - reduced to Italy and a few scattered provinces.",
    },
    {
        "title": "Fall of the Western Roman Empire",
        "year": 476,
        "display_date": "476 CE",
        "category": "Rome",
        "icon": "📉",
        "summary": "Germanic general Odoacer deposes the last Western Roman emperor, Romulus Augustulus - a teenager - and doesn't bother naming a replacement. After five centuries as an empire, Rome's western half simply ceases to exist.",
        "leads_to": "Its legions and emperors are gone, but Rome's laws, language, architecture, and legends go on to shape the world for the next 1,500 years and beyond.",
    },
]
