"""Seed dataset of historical events for the timeline app.

Years use astronomical numbering: BCE years are negative (e.g. 753 BCE -> -753).
This keeps the year field numeric and sortable for plotting.
"""

EVENTS = [
    # --- Rome ---
    {
        "title": "Founding of Rome",
        "year": -753,
        "display_date": "753 BCE",
        "category": "Rome",
        "icon": "🐺",
        "summary": "Legendary founding of the city by Romulus, who allegedly kills his twin brother Remus in a dispute over where to build.",
    },
    {
        "title": "Hannibal Crosses the Alps",
        "year": -218,
        "display_date": "218 BCE",
        "category": "Rome",
        "icon": "🐘",
        "summary": "Carthaginian general Hannibal leads an army, including war elephants, over the Alps to invade Italy during the Second Punic War.",
    },
    {
        "title": "\"Carthago Delenda Est\"",
        "year": -146,
        "display_date": "146 BCE",
        "category": "Rome",
        "icon": "🏚️",
        "summary": "Cato the Elder ends every Senate speech with \"Carthago delenda est\" - Carthage must be destroyed. Rome finally besieges and razes the city at the end of the Third Punic War.",
    },
    {
        "title": "Caesar's Conquest of Gaul",
        "year": -58,
        "display_date": "58-50 BCE",
        "category": "Rome",
        "icon": "⚔️",
        "summary": "Julius Caesar conquers Gaul over nearly a decade of campaigning, cementing his military reputation and wealth.",
    },
    {
        "title": "Caesar Crosses the Rubicon",
        "year": -49,
        "display_date": "49 BCE",
        "category": "Rome",
        "icon": "🎲",
        "summary": "Caesar leads his army across the Rubicon River into Italy, an act of war against the Senate. \"Alea iacta est\" - the die is cast.",
    },
    {
        "title": "Caesar and Cleopatra",
        "year": -48,
        "display_date": "48 BCE",
        "category": "Rome",
        "icon": "👑",
        "summary": "Caesar arrives in Egypt pursuing his rival Pompey and becomes entangled with Cleopatra, backing her claim to the Egyptian throne.",
    },
    {
        "title": "\"Veni, Vidi, Vici\"",
        "year": -47,
        "display_date": "47 BCE",
        "category": "Rome",
        "icon": "🏆",
        "summary": "Caesar reports his lightning victory over King Pharnaces II at the Battle of Zela in three words: \"I came, I saw, I conquered.\"",
    },
    {
        "title": "Assassination of Julius Caesar",
        "year": -44,
        "display_date": "44 BCE",
        "category": "Rome",
        "icon": "🗡️",
        "summary": "Caesar is stabbed to death by a group of senators, including Brutus, on the Ides of March. \"Et tu, Brute?\"",
    },
    {
        "title": "Battle of Actium",
        "year": -31,
        "display_date": "31 BCE",
        "category": "Rome",
        "icon": "⚓",
        "summary": "Octavian's fleet crushes the combined forces of Mark Antony and Cleopatra, deciding the fate of Rome and Egypt.",
    },
    {
        "title": "Death of Cleopatra",
        "year": -30,
        "display_date": "30 BCE",
        "category": "Rome",
        "icon": "🐍",
        "summary": "Cleopatra VII, last pharaoh of Egypt, dies by suicide (legend says by asp bite) as Octavian's forces take Alexandria, ending Ptolemaic Egypt.",
    },
    {
        "title": "Augustus and the Pax Romana",
        "year": -27,
        "display_date": "27 BCE",
        "category": "Rome",
        "icon": "🏛️",
        "summary": "Octavian is granted the title Augustus and becomes Rome's first emperor, beginning two centuries of relative peace and stability.",
    },
    {
        "title": "\"Carpe Diem\" Coined",
        "year": -23,
        "display_date": "23 BCE",
        "category": "Rome",
        "icon": "⏳",
        "summary": "The poet Horace writes \"carpe diem\" - seize the day - in his Odes, coining one of the most quoted phrases in the world.",
    },
    {
        "title": "\"We Who Are About to Die Salute You\"",
        "year": 52,
        "display_date": "52 CE",
        "category": "Rome",
        "icon": "🤺",
        "summary": "Condemned fighters reportedly greet Emperor Claudius with \"Ave Imperator, morituri te salutant\" before a staged naval battle - a phrase now inseparable from pop culture's idea of the gladiator.",
    },
    {
        "title": "The Colosseum Opens",
        "year": 80,
        "display_date": "80 CE",
        "category": "Rome",
        "icon": "🏟️",
        "summary": "The Flavian Amphitheatre opens with 100 days of games, hosting gladiatorial combat for the next several centuries.",
    },
    {
        "title": "Vesuvius Erupts, Pompeii Buried",
        "year": 79,
        "display_date": "79 CE",
        "category": "Rome",
        "icon": "🌋",
        "summary": "Mount Vesuvius erupts and buries Pompeii and Herculaneum in ash, preserving them - and their residents - almost perfectly for archaeologists.",
    },
    {
        "title": "\"Bread and Circuses\"",
        "year": 100,
        "display_date": "c. 100 CE",
        "category": "Rome",
        "icon": "🎪",
        "summary": "Satirist Juvenal coins \"panem et circenses\" - bread and circuses - describing how free food and games kept the Roman public docile.",
    },
    {
        "title": "Edict of Milan",
        "year": 313,
        "display_date": "313 CE",
        "category": "Rome",
        "icon": "✝️",
        "summary": "Emperor Constantine legalizes Christianity throughout the Roman Empire, ending centuries of persecution.",
    },

    # --- Constantinople / Istanbul ---
    {
        "title": "Founding of Constantinople",
        "year": 330,
        "display_date": "330 CE",
        "category": "Istanbul",
        "icon": "🏙️",
        "summary": "Constantine dedicates the city of Byzantium as his new capital, \"New Rome\" - later known as Constantinople.",
    },
    {
        "title": "Fall of the Western Roman Empire",
        "year": 476,
        "display_date": "476 CE",
        "category": "Istanbul",
        "icon": "📉",
        "summary": "The last Western Roman emperor, Romulus Augustulus, is deposed. The Eastern Empire, centered on Constantinople, carries on as Byzantium.",
    },
    {
        "title": "Hagia Sophia Completed",
        "year": 537,
        "display_date": "537 CE",
        "category": "Istanbul",
        "icon": "⛪",
        "summary": "Emperor Justinian completes the Hagia Sophia, the largest cathedral in the world for nearly a thousand years.",
    },
    {
        "title": "The Great Schism",
        "year": 1054,
        "display_date": "1054 CE",
        "category": "Istanbul",
        "icon": "🔀",
        "summary": "The Christian Church formally splits into the Roman Catholic and Eastern Orthodox branches.",
    },
    {
        "title": "Fourth Crusade Sacks Constantinople",
        "year": 1204,
        "display_date": "1204 CE",
        "category": "Istanbul",
        "icon": "🔥",
        "summary": "Crusaders bound for the Holy Land instead sack the Christian city of Constantinople, permanently weakening the Byzantine Empire.",
    },
    {
        "title": "Fall of Constantinople",
        "year": 1453,
        "display_date": "1453 CE",
        "category": "Istanbul",
        "icon": "🕌",
        "summary": "Ottoman Sultan Mehmed II conquers Constantinople, ending the Byzantine Empire. The Hagia Sophia becomes a mosque.",
    },
    {
        "title": "Suleiman the Magnificent's Golden Age",
        "year": 1520,
        "display_date": "1520s CE",
        "category": "Istanbul",
        "icon": "👑",
        "summary": "Suleiman I presides over the Ottoman Empire's peak of military, political, and cultural power.",
    },
    {
        "title": "Turkish Republic Founded",
        "year": 1923,
        "display_date": "1923 CE",
        "category": "Istanbul",
        "icon": "🇹🇷",
        "summary": "Mustafa Kemal Atatürk founds the Republic of Turkey, ending the Ottoman Empire. The capital moves to Ankara.",
    },

    # --- World History Hits ---
    {
        "title": "Viking Raid on Lindisfarne",
        "year": 793,
        "display_date": "793 CE",
        "category": "World History",
        "icon": "🪓",
        "summary": "Norse raiders attack the monastery of Lindisfarne, marking the traditional start of the Viking Age in Europe.",
    },
    {
        "title": "Battle of Hastings",
        "year": 1066,
        "display_date": "1066 CE",
        "category": "World History",
        "icon": "🏹",
        "summary": "William the Conqueror defeats King Harold II, beginning the Norman conquest of England.",
    },
    {
        "title": "Magna Carta Signed",
        "year": 1215,
        "display_date": "1215 CE",
        "category": "World History",
        "icon": "📜",
        "summary": "King John of England is forced to accept limits on royal power, laying groundwork for constitutional law.",
    },
    {
        "title": "Genghis Khan Unites the Mongols",
        "year": 1206,
        "display_date": "1206 CE",
        "category": "World History",
        "icon": "🐎",
        "summary": "Genghis Khan unites the Mongol tribes and begins building the largest contiguous land empire in history.",
    },
    {
        "title": "The Black Death",
        "year": 1347,
        "display_date": "1347-1351 CE",
        "category": "World History",
        "icon": "💀",
        "summary": "The bubonic plague sweeps through Europe, killing an estimated third of the population.",
    },
    {
        "title": "Gutenberg's Printing Press",
        "year": 1440,
        "display_date": "c. 1440 CE",
        "category": "World History",
        "icon": "🖨️",
        "summary": "Johannes Gutenberg develops the movable-type printing press, revolutionizing the spread of information.",
    },
    {
        "title": "Columbus Reaches the Americas",
        "year": 1492,
        "display_date": "1492 CE",
        "category": "World History",
        "icon": "⛵",
        "summary": "Christopher Columbus makes landfall in the Caribbean, beginning sustained European contact with the Americas.",
    },
    {
        "title": "The Mona Lisa is Painted",
        "year": 1503,
        "display_date": "c. 1503 CE",
        "category": "World History",
        "icon": "🎨",
        "summary": "Leonardo da Vinci begins painting what will become the most famous portrait in the world.",
    },
    {
        "title": "Luther's 95 Theses",
        "year": 1517,
        "display_date": "1517 CE",
        "category": "World History",
        "icon": "🔨",
        "summary": "Martin Luther publishes his critique of the Catholic Church, sparking the Protestant Reformation.",
    },
    {
        "title": "Salem Witch Trials",
        "year": 1692,
        "display_date": "1692 CE",
        "category": "World History",
        "icon": "🧙",
        "summary": "A wave of hysteria in colonial Massachusetts leads to the execution of twenty people accused of witchcraft.",
    },
    {
        "title": "U.S. Declaration of Independence",
        "year": 1776,
        "display_date": "1776 CE",
        "category": "World History",
        "icon": "🇺🇸",
        "summary": "The thirteen American colonies formally declare independence from Great Britain.",
    },
    {
        "title": "Storming of the Bastille",
        "year": 1789,
        "display_date": "1789 CE",
        "category": "World History",
        "icon": "🏰",
        "summary": "Parisians storm the Bastille fortress, igniting the French Revolution.",
    },
    {
        "title": "Execution of Marie Antoinette",
        "year": 1793,
        "display_date": "1793 CE",
        "category": "World History",
        "icon": "🔪",
        "summary": "The former queen of France is guillotined during the Reign of Terror.",
    },
    {
        "title": "Battle of Waterloo",
        "year": 1815,
        "display_date": "1815 CE",
        "category": "World History",
        "icon": "🎖️",
        "summary": "Napoleon Bonaparte is decisively defeated, ending his rule and reshaping the map of Europe.",
    },
    {
        "title": "U.S. Civil War",
        "year": 1861,
        "display_date": "1861-1865 CE",
        "category": "World History",
        "icon": "⛓️",
        "summary": "The Union and Confederacy fight over slavery and secession; the war ends with slavery's abolition and the Union preserved.",
    },
    {
        "title": "Titanic Sinks",
        "year": 1912,
        "display_date": "1912 CE",
        "category": "World History",
        "icon": "🧊",
        "summary": "The \"unsinkable\" RMS Titanic strikes an iceberg and sinks on its maiden voyage, killing over 1,500 people.",
    },
    {
        "title": "Assassination of Franz Ferdinand",
        "year": 1914,
        "display_date": "1914 CE",
        "category": "World History",
        "icon": "🔫",
        "summary": "The assassination of the Austro-Hungarian archduke in Sarajevo triggers the outbreak of World War I.",
    },
    {
        "title": "Russian Revolution",
        "year": 1917,
        "display_date": "1917 CE",
        "category": "World History",
        "icon": "🚩",
        "summary": "Bolsheviks seize power in Russia, overthrowing the Tsar and eventually forming the Soviet Union.",
    },
    {
        "title": "Prohibition Begins",
        "year": 1920,
        "display_date": "1920 CE",
        "category": "World History",
        "icon": "🍸",
        "summary": "The U.S. bans alcohol, fueling the rise of organized crime figures like Al Capone.",
    },
    {
        "title": "The Great Depression Begins",
        "year": 1929,
        "display_date": "1929 CE",
        "category": "World History",
        "icon": "📉",
        "summary": "The Wall Street Crash triggers a decade-long global economic depression.",
    },
    {
        "title": "World War II",
        "year": 1939,
        "display_date": "1939-1945 CE",
        "category": "World History",
        "icon": "💣",
        "summary": "The deadliest conflict in history, spanning the globe and including the Holocaust and the atomic bombings of Japan.",
    },
    {
        "title": "Moon Landing",
        "year": 1969,
        "display_date": "1969 CE",
        "category": "World History",
        "icon": "🚀",
        "summary": "Apollo 11 astronauts Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon.",
    },
    {
        "title": "Fall of the Berlin Wall",
        "year": 1989,
        "display_date": "1989 CE",
        "category": "World History",
        "icon": "🧱",
        "summary": "East Germans breach the Berlin Wall, symbolizing the end of the Cold War division of Europe.",
    },
    {
        "title": "September 11 Attacks",
        "year": 2001,
        "display_date": "2001 CE",
        "category": "World History",
        "icon": "🏢",
        "summary": "Terrorist attacks on the World Trade Center and Pentagon reshape U.S. foreign policy for decades.",
    },
]
